# Generated by Django 5.2 on 2025-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("emergency_contact", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("address", models.CharField(max_length=200)),
                (
                    "interested_course",
                    models.CharField(
                        choices=[
                            ("Photography", "Photography"),
                            ("Videography", "Videography"),
                            ("Web Development", "Web Development"),
                        ],
                        max_length=20,
                    ),
                ),
                ("device", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="registrations/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
